[package]
name = "bmputil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0"
env_logger = "0.9"
dfu-core = { version = "0.2", features = ["std"] }
dfu-libusb = "0.2"
rusb = "0.9"
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"

[patch.crates-io]
# Required until https://github.com/dfu-rs/dfu-core/pull/9 is merged.
dfu-core = { git = "https://github.com/dfu-rs/dfu-core", branch = "cecton-add-set-address" }
