# We don't actually want rustfmt to do all the formatting, as there isn't enough granularity.
# Therefore, any options that follow this one are symbolic as guidelines, rather than rules
# for rustfmt.
#disable_all_formatting = true

array_width = 80
binop_separator = "Back"
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2024"
empty_item_single_line = true
fn_call_width = 80
format_code_in_doc_comments = true
doc_comment_code_block_width = 120
format_strings = true
#hard_tabs = true
hex_literal_case = "Lower"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
struct_lit_single_line = false
style_edition = "2024"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
